public class org.javia.arity.ArityException extends java.lang.RuntimeException
{

    public void <init>(java.lang.String)
    {
        org.javia.arity.ArityException r0;
        java.lang.String r1;

        r0 := @this: org.javia.arity.ArityException;

        r1 := @parameter0: java.lang.String;

        specialinvoke r0.<java.lang.RuntimeException: void <init>(java.lang.String)>(r1);

        return;
    }

    public void <init>(int)
    {
        org.javia.arity.ArityException r0;
        int i0;
        java.lang.StringBuilder $r1, $r2, $r3, $r4;
        java.lang.String $r5;

        r0 := @this: org.javia.arity.ArityException;

        i0 := @parameter0: int;

        $r1 = new java.lang.StringBuilder;

        specialinvoke $r1.<java.lang.StringBuilder: void <init>()>();

        $r2 = virtualinvoke $r1.<java.lang.StringBuilder: java.lang.StringBuilder append(java.lang.String)>("Didn\'t expect ");

        $r3 = virtualinvoke $r2.<java.lang.StringBuilder: java.lang.StringBuilder append(int)>(i0);

        $r4 = virtualinvoke $r3.<java.lang.StringBuilder: java.lang.StringBuilder append(java.lang.String)>(" arguments");

        $r5 = virtualinvoke $r4.<java.lang.StringBuilder: java.lang.String toString()>();

        specialinvoke r0.<org.javia.arity.ArityException: void <init>(java.lang.String)>($r5);

        return;
    }
}
