public class junit.framework.TestResult extends java.lang.Object
{
    protected java.util.Vector fErrors;
    protected java.util.Vector fFailures;
    protected java.util.Vector fListeners;
    protected int fRunTests;
    private boolean fStop;

    public void <init>()
    {
        junit.framework.TestResult r0;
        java.util.Vector $r1, $r2, $r3;

        r0 := @this: junit.framework.TestResult;

        specialinvoke r0.<java.lang.Object: void <init>()>();

        $r1 = new java.util.Vector;

        specialinvoke $r1.<java.util.Vector: void <init>()>();

        r0.<junit.framework.TestResult: java.util.Vector fFailures> = $r1;

        $r2 = new java.util.Vector;

        specialinvoke $r2.<java.util.Vector: void <init>()>();

        r0.<junit.framework.TestResult: java.util.Vector fErrors> = $r2;

        $r3 = new java.util.Vector;

        specialinvoke $r3.<java.util.Vector: void <init>()>();

        r0.<junit.framework.TestResult: java.util.Vector fListeners> = $r3;

        r0.<junit.framework.TestResult: int fRunTests> = 0;

        r0.<junit.framework.TestResult: boolean fStop> = 0;

        return;
    }

    private java.util.List cloneListeners()
    {
        junit.framework.TestResult r0;
        java.util.ArrayList r1, $r3;
        java.lang.Throwable r2, $r5;
        java.util.Vector $r4;

        r0 := @this: junit.framework.TestResult;

        entermonitor r0;

     label1:
        $r3 = new java.util.ArrayList;

        specialinvoke $r3.<java.util.ArrayList: void <init>()>();

        r1 = $r3;

        $r4 = r0.<junit.framework.TestResult: java.util.Vector fListeners>;

        interfaceinvoke r1.<java.util.List: boolean addAll(java.util.Collection)>($r4);

     label2:
        exitmonitor r0;

        return r1;

     label3:
        $r5 := @caughtexception;

        r2 = $r5;

        exitmonitor r0;

        throw r2;

        catch java.lang.Throwable from label1 to label2 with label3;
    }

    public void addError(junit.framework.Test, java.lang.Throwable)
    {
        junit.framework.TestResult r0;
        junit.framework.Test r1;
        java.lang.Throwable r2, r3, $r10;
        java.util.Iterator r4;
        junit.framework.TestFailure $r5;
        java.util.Vector $r6;
        java.util.List $r7;
        boolean $z1;
        java.lang.Object $r8;
        junit.framework.TestListener $r9;

        r0 := @this: junit.framework.TestResult;

        r1 := @parameter0: junit.framework.Test;

        r2 := @parameter1: java.lang.Throwable;

        entermonitor r0;

     label1:
        $r6 = r0.<junit.framework.TestResult: java.util.Vector fErrors>;

        $r5 = new junit.framework.TestFailure;

        specialinvoke $r5.<junit.framework.TestFailure: void <init>(junit.framework.Test,java.lang.Throwable)>(r1, r2);

        virtualinvoke $r6.<java.util.Vector: boolean add(java.lang.Object)>($r5);

        $r7 = specialinvoke r0.<junit.framework.TestResult: java.util.List cloneListeners()>();

        r4 = interfaceinvoke $r7.<java.util.List: java.util.Iterator iterator()>();

     label2:
        $z1 = interfaceinvoke r4.<java.util.Iterator: boolean hasNext()>();

        if $z1 == 0 goto label5;

        $r8 = interfaceinvoke r4.<java.util.Iterator: java.lang.Object next()>();

        $r9 = (junit.framework.TestListener) $r8;

        interfaceinvoke $r9.<junit.framework.TestListener: void addError(junit.framework.Test,java.lang.Throwable)>(r1, r2);

     label3:
        goto label2;

     label4:
        $r10 := @caughtexception;

        r3 = $r10;

        exitmonitor r0;

        throw r3;

     label5:
        exitmonitor r0;

        return;

        catch java.lang.Throwable from label1 to label2 with label4;
        catch java.lang.Throwable from label2 to label3 with label4;
    }

    public void addFailure(junit.framework.Test, junit.framework.AssertionFailedError)
    {
        junit.framework.TestResult r0;
        junit.framework.Test r1;
        junit.framework.AssertionFailedError r2;
        java.lang.Throwable r3, $r10;
        java.util.Iterator r4;
        junit.framework.TestFailure $r5;
        java.util.Vector $r6;
        java.util.List $r7;
        boolean $z1;
        java.lang.Object $r8;
        junit.framework.TestListener $r9;

        r0 := @this: junit.framework.TestResult;

        r1 := @parameter0: junit.framework.Test;

        r2 := @parameter1: junit.framework.AssertionFailedError;

        entermonitor r0;

     label1:
        $r6 = r0.<junit.framework.TestResult: java.util.Vector fFailures>;

        $r5 = new junit.framework.TestFailure;

        specialinvoke $r5.<junit.framework.TestFailure: void <init>(junit.framework.Test,java.lang.Throwable)>(r1, r2);

        virtualinvoke $r6.<java.util.Vector: boolean add(java.lang.Object)>($r5);

        $r7 = specialinvoke r0.<junit.framework.TestResult: java.util.List cloneListeners()>();

        r4 = interfaceinvoke $r7.<java.util.List: java.util.Iterator iterator()>();

     label2:
        $z1 = interfaceinvoke r4.<java.util.Iterator: boolean hasNext()>();

        if $z1 == 0 goto label5;

        $r8 = interfaceinvoke r4.<java.util.Iterator: java.lang.Object next()>();

        $r9 = (junit.framework.TestListener) $r8;

        interfaceinvoke $r9.<junit.framework.TestListener: void addFailure(junit.framework.Test,junit.framework.AssertionFailedError)>(r1, r2);

     label3:
        goto label2;

     label4:
        $r10 := @caughtexception;

        r3 = $r10;

        exitmonitor r0;

        throw r3;

     label5:
        exitmonitor r0;

        return;

        catch java.lang.Throwable from label1 to label2 with label4;
        catch java.lang.Throwable from label2 to label3 with label4;
    }

    public void addListener(junit.framework.TestListener)
    {
        junit.framework.TestResult r0;
        junit.framework.TestListener r1;
        java.lang.Throwable r2, $r4;
        java.util.Vector $r3;

        r0 := @this: junit.framework.TestResult;

        r1 := @parameter0: junit.framework.TestListener;

        entermonitor r0;

     label1:
        $r3 = r0.<junit.framework.TestResult: java.util.Vector fListeners>;

        virtualinvoke $r3.<java.util.Vector: boolean add(java.lang.Object)>(r1);

     label2:
        exitmonitor r0;

        return;

     label3:
        $r4 := @caughtexception;

        r2 = $r4;

        exitmonitor r0;

        throw r2;

        catch java.lang.Throwable from label1 to label2 with label3;
    }

    public void endTest(junit.framework.Test)
    {
        junit.framework.TestResult r0;
        junit.framework.Test r1;
        java.util.Iterator r2;
        java.util.List $r3;
        boolean $z0;
        java.lang.Object $r4;
        junit.framework.TestListener $r5;

        r0 := @this: junit.framework.TestResult;

        r1 := @parameter0: junit.framework.Test;

        $r3 = specialinvoke r0.<junit.framework.TestResult: java.util.List cloneListeners()>();

        r2 = interfaceinvoke $r3.<java.util.List: java.util.Iterator iterator()>();

     label1:
        $z0 = interfaceinvoke r2.<java.util.Iterator: boolean hasNext()>();

        if $z0 == 0 goto label2;

        $r4 = interfaceinvoke r2.<java.util.Iterator: java.lang.Object next()>();

        $r5 = (junit.framework.TestListener) $r4;

        interfaceinvoke $r5.<junit.framework.TestListener: void endTest(junit.framework.Test)>(r1);

        goto label1;

     label2:
        return;
    }

    public int errorCount()
    {
        junit.framework.TestResult r0;
        java.lang.Throwable r1, $r3;
        int i0;
        java.util.Vector $r2;

        r0 := @this: junit.framework.TestResult;

        entermonitor r0;

     label1:
        $r2 = r0.<junit.framework.TestResult: java.util.Vector fErrors>;

        i0 = virtualinvoke $r2.<java.util.Vector: int size()>();

     label2:
        exitmonitor r0;

        return i0;

     label3:
        $r3 := @caughtexception;

        r1 = $r3;

        exitmonitor r0;

        throw r1;

        catch java.lang.Throwable from label1 to label2 with label3;
    }

    public java.util.Enumeration errors()
    {
        junit.framework.TestResult r0;
        java.lang.Throwable r1, $r4;
        java.util.Enumeration r2;
        java.util.Vector $r3;

        r0 := @this: junit.framework.TestResult;

        entermonitor r0;

     label1:
        $r3 = r0.<junit.framework.TestResult: java.util.Vector fErrors>;

        r2 = staticinvoke <java.util.Collections: java.util.Enumeration enumeration(java.util.Collection)>($r3);

     label2:
        exitmonitor r0;

        return r2;

     label3:
        $r4 := @caughtexception;

        r1 = $r4;

        exitmonitor r0;

        throw r1;

        catch java.lang.Throwable from label1 to label2 with label3;
    }

    public int failureCount()
    {
        junit.framework.TestResult r0;
        java.lang.Throwable r1, $r3;
        int i0;
        java.util.Vector $r2;

        r0 := @this: junit.framework.TestResult;

        entermonitor r0;

     label1:
        $r2 = r0.<junit.framework.TestResult: java.util.Vector fFailures>;

        i0 = virtualinvoke $r2.<java.util.Vector: int size()>();

     label2:
        exitmonitor r0;

        return i0;

     label3:
        $r3 := @caughtexception;

        r1 = $r3;

        exitmonitor r0;

        throw r1;

        catch java.lang.Throwable from label1 to label2 with label3;
    }

    public java.util.Enumeration failures()
    {
        junit.framework.TestResult r0;
        java.lang.Throwable r1, $r4;
        java.util.Enumeration r2;
        java.util.Vector $r3;

        r0 := @this: junit.framework.TestResult;

        entermonitor r0;

     label1:
        $r3 = r0.<junit.framework.TestResult: java.util.Vector fFailures>;

        r2 = staticinvoke <java.util.Collections: java.util.Enumeration enumeration(java.util.Collection)>($r3);

     label2:
        exitmonitor r0;

        return r2;

     label3:
        $r4 := @caughtexception;

        r1 = $r4;

        exitmonitor r0;

        throw r1;

        catch java.lang.Throwable from label1 to label2 with label3;
    }

    public void removeListener(junit.framework.TestListener)
    {
        junit.framework.TestResult r0;
        junit.framework.TestListener r1;
        java.lang.Throwable r2, $r4;
        java.util.Vector $r3;

        r0 := @this: junit.framework.TestResult;

        r1 := @parameter0: junit.framework.TestListener;

        entermonitor r0;

     label1:
        $r3 = r0.<junit.framework.TestResult: java.util.Vector fListeners>;

        virtualinvoke $r3.<java.util.Vector: boolean remove(java.lang.Object)>(r1);

     label2:
        exitmonitor r0;

        return;

     label3:
        $r4 := @caughtexception;

        r2 = $r4;

        exitmonitor r0;

        throw r2;

        catch java.lang.Throwable from label1 to label2 with label3;
    }

    protected void run(junit.framework.TestCase)
    {
        junit.framework.TestResult r0;
        junit.framework.TestCase r1;
        junit.framework.TestResult$1 $r2;

        r0 := @this: junit.framework.TestResult;

        r1 := @parameter0: junit.framework.TestCase;

        virtualinvoke r0.<junit.framework.TestResult: void startTest(junit.framework.Test)>(r1);

        $r2 = new junit.framework.TestResult$1;

        specialinvoke $r2.<junit.framework.TestResult$1: void <init>(junit.framework.TestResult,junit.framework.TestCase)>(r0, r1);

        virtualinvoke r0.<junit.framework.TestResult: void runProtected(junit.framework.Test,junit.framework.Protectable)>(r1, $r2);

        virtualinvoke r0.<junit.framework.TestResult: void endTest(junit.framework.Test)>(r1);

        return;
    }

    public int runCount()
    {
        junit.framework.TestResult r0;
        java.lang.Throwable r1, $r2;
        int i0;

        r0 := @this: junit.framework.TestResult;

        entermonitor r0;

     label1:
        i0 = r0.<junit.framework.TestResult: int fRunTests>;

     label2:
        exitmonitor r0;

        return i0;

     label3:
        $r2 := @caughtexception;

        r1 = $r2;

        exitmonitor r0;

        throw r1;

        catch java.lang.Throwable from label1 to label2 with label3;
    }

    public void runProtected(junit.framework.Test, junit.framework.Protectable)
    {
        junit.framework.TestResult r0;
        junit.framework.Test r1;
        junit.framework.Protectable r2;
        java.lang.Throwable r3, $r6;
        java.lang.ThreadDeath r4, $r8;
        junit.framework.AssertionFailedError r5, $r7;

        r0 := @this: junit.framework.TestResult;

        r1 := @parameter0: junit.framework.Test;

        r2 := @parameter1: junit.framework.Protectable;

     label1:
        interfaceinvoke r2.<junit.framework.Protectable: void protect()>();

     label2:
        return;

     label3:
        $r7 := @caughtexception;

        r5 = $r7;

        virtualinvoke r0.<junit.framework.TestResult: void addFailure(junit.framework.Test,junit.framework.AssertionFailedError)>(r1, r5);

        return;

     label4:
        $r8 := @caughtexception;

        r4 = $r8;

        throw r4;

     label5:
        $r6 := @caughtexception;

        r3 = $r6;

        virtualinvoke r0.<junit.framework.TestResult: void addError(junit.framework.Test,java.lang.Throwable)>(r1, r3);

        return;

        catch junit.framework.AssertionFailedError from label1 to label2 with label3;
        catch java.lang.ThreadDeath from label1 to label2 with label4;
        catch java.lang.Throwable from label1 to label2 with label5;
    }

    public boolean shouldStop()
    {
        junit.framework.TestResult r0;
        java.lang.Throwable r1, $r2;
        boolean z0;

        r0 := @this: junit.framework.TestResult;

        entermonitor r0;

     label1:
        z0 = r0.<junit.framework.TestResult: boolean fStop>;

     label2:
        exitmonitor r0;

        return z0;

     label3:
        $r2 := @caughtexception;

        r1 = $r2;

        exitmonitor r0;

        throw r1;

        catch java.lang.Throwable from label1 to label2 with label3;
    }

    public void startTest(junit.framework.Test)
    {
        junit.framework.TestResult r0;
        junit.framework.Test r1;
        int i0, $i1, $i2;
        java.lang.Throwable r2, $r7;
        java.util.Iterator r3;
        java.util.List $r4;
        boolean $z0;
        java.lang.Object $r5;
        junit.framework.TestListener $r6;

        r0 := @this: junit.framework.TestResult;

        r1 := @parameter0: junit.framework.Test;

        i0 = interfaceinvoke r1.<junit.framework.Test: int countTestCases()>();

        entermonitor r0;

     label1:
        $i1 = r0.<junit.framework.TestResult: int fRunTests>;

        $i2 = i0 + $i1;

        r0.<junit.framework.TestResult: int fRunTests> = $i2;

        exitmonitor r0;

     label2:
        $r4 = specialinvoke r0.<junit.framework.TestResult: java.util.List cloneListeners()>();

        r3 = interfaceinvoke $r4.<java.util.List: java.util.Iterator iterator()>();

     label3:
        $z0 = interfaceinvoke r3.<java.util.Iterator: boolean hasNext()>();

        if $z0 == 0 goto label7;

        $r5 = interfaceinvoke r3.<java.util.Iterator: java.lang.Object next()>();

        $r6 = (junit.framework.TestListener) $r5;

        interfaceinvoke $r6.<junit.framework.TestListener: void startTest(junit.framework.Test)>(r1);

        goto label3;

     label4:
        $r7 := @caughtexception;

        r2 = $r7;

     label5:
        exitmonitor r0;

     label6:
        throw r2;

     label7:
        return;

        catch java.lang.Throwable from label1 to label2 with label4;
        catch java.lang.Throwable from label5 to label6 with label4;
    }

    public void stop()
    {
        junit.framework.TestResult r0;
        java.lang.Throwable r1, $r2;

        r0 := @this: junit.framework.TestResult;

        entermonitor r0;

     label1:
        r0.<junit.framework.TestResult: boolean fStop> = 1;

     label2:
        exitmonitor r0;

        return;

     label3:
        $r2 := @caughtexception;

        r1 = $r2;

        exitmonitor r0;

        throw r1;

        catch java.lang.Throwable from label1 to label2 with label3;
    }

    public boolean wasSuccessful()
    {
        junit.framework.TestResult r0;
        java.lang.Throwable r1, $r2;
        boolean z0;
        int i0, $i1;

        r0 := @this: junit.framework.TestResult;

        entermonitor r0;

     label1:
        $i1 = virtualinvoke r0.<junit.framework.TestResult: int failureCount()>();

        if $i1 != 0 goto label4;

        i0 = virtualinvoke r0.<junit.framework.TestResult: int errorCount()>();

     label2:
        if i0 != 0 goto label4;

        z0 = 1;

     label3:
        exitmonitor r0;

        return z0;

     label4:
        z0 = 0;

        goto label3;

     label5:
        $r2 := @caughtexception;

        r1 = $r2;

        exitmonitor r0;

        throw r1;

        catch java.lang.Throwable from label1 to label2 with label5;
    }
}
