class android.support.v4.content.ModernAsyncTask$3 extends java.util.concurrent.FutureTask
{
    final android.support.v4.content.ModernAsyncTask this$0;

    void <init>(android.support.v4.content.ModernAsyncTask, java.util.concurrent.Callable)
    {
        android.support.v4.content.ModernAsyncTask$3 r0;
        android.support.v4.content.ModernAsyncTask r1;
        java.util.concurrent.Callable r2;

        r0 := @this: android.support.v4.content.ModernAsyncTask$3;

        r1 := @parameter0: android.support.v4.content.ModernAsyncTask;

        r2 := @parameter1: java.util.concurrent.Callable;

        r0.<android.support.v4.content.ModernAsyncTask$3: android.support.v4.content.ModernAsyncTask this$0> = r1;

        specialinvoke r0.<java.util.concurrent.FutureTask: void <init>(java.util.concurrent.Callable)>(r2);

        return;
    }

    protected void done()
    {
        android.support.v4.content.ModernAsyncTask$3 r0;
        java.lang.Object r1;
        android.support.v4.content.ModernAsyncTask $r2, $r10;
        java.lang.Throwable $r3, $r8, r14;
        java.lang.RuntimeException $r4, $r7;
        java.lang.InterruptedException $r5, r11;
        java.util.concurrent.ExecutionException $r6, r12;
        java.util.concurrent.CancellationException $r9;

        r0 := @this: android.support.v4.content.ModernAsyncTask$3;

     label1:
        r1 = virtualinvoke r0.<android.support.v4.content.ModernAsyncTask$3: java.lang.Object get()>();

        $r2 = r0.<android.support.v4.content.ModernAsyncTask$3: android.support.v4.content.ModernAsyncTask this$0>;

        staticinvoke <android.support.v4.content.ModernAsyncTask: void access$400(android.support.v4.content.ModernAsyncTask,java.lang.Object)>($r2, r1);

     label2:
        goto label7;

     label3:
        $r5 := @caughtexception;

        r11 = $r5;

        staticinvoke <android.util.Log: int w(java.lang.String,java.lang.Throwable)>("AsyncTask", r11);

        goto label7;

     label4:
        $r6 := @caughtexception;

        r12 = $r6;

        $r7 = new java.lang.RuntimeException;

        $r8 = virtualinvoke r12.<java.util.concurrent.ExecutionException: java.lang.Throwable getCause()>();

        specialinvoke $r7.<java.lang.RuntimeException: void <init>(java.lang.String,java.lang.Throwable)>("An error occured while executing doInBackground()", $r8);

        throw $r7;

     label5:
        $r9 := @caughtexception;

        $r10 = r0.<android.support.v4.content.ModernAsyncTask$3: android.support.v4.content.ModernAsyncTask this$0>;

        staticinvoke <android.support.v4.content.ModernAsyncTask: void access$400(android.support.v4.content.ModernAsyncTask,java.lang.Object)>($r10, null);

        goto label7;

     label6:
        $r3 := @caughtexception;

        r14 = $r3;

        $r4 = new java.lang.RuntimeException;

        specialinvoke $r4.<java.lang.RuntimeException: void <init>(java.lang.String,java.lang.Throwable)>("An error occured while executing doInBackground()", r14);

        throw $r4;

     label7:
        return;

        catch java.lang.InterruptedException from label1 to label2 with label3;
        catch java.util.concurrent.ExecutionException from label1 to label2 with label4;
        catch java.util.concurrent.CancellationException from label1 to label2 with label5;
        catch java.lang.Throwable from label1 to label2 with label6;
    }
}
