public class com.android.internal.os.ZygoteInit$MethodAndArgsCaller extends java.lang.Exception implements java.lang.Runnable
{
    private final java.lang.String[] mArgs;
    private final java.lang.reflect.Method mMethod;

    public void <init>(java.lang.reflect.Method, java.lang.String[])
    {
        com.android.internal.os.ZygoteInit$MethodAndArgsCaller r0;
        java.lang.reflect.Method r1;
        java.lang.String[] r2;

        r0 := @this: com.android.internal.os.ZygoteInit$MethodAndArgsCaller;

        r1 := @parameter0: java.lang.reflect.Method;

        r2 := @parameter1: java.lang.String[];

        specialinvoke r0.<java.lang.Exception: void <init>()>();

        r0.<com.android.internal.os.ZygoteInit$MethodAndArgsCaller: java.lang.reflect.Method mMethod> = r1;

        r0.<com.android.internal.os.ZygoteInit$MethodAndArgsCaller: java.lang.String[] mArgs> = r2;

        return;
    }

    public void run()
    {
        com.android.internal.os.ZygoteInit$MethodAndArgsCaller r0;
        java.lang.reflect.InvocationTargetException r1, $r10;
        java.lang.Throwable r2;
        java.lang.IllegalAccessException r3, $r8;
        java.lang.reflect.Method r4;
        java.lang.Object[] r5;
        java.lang.String[] $r6;
        java.lang.RuntimeException $r9, $r11, $r13;
        boolean $z0, $z1;
        java.lang.Error $r12;

        r0 := @this: com.android.internal.os.ZygoteInit$MethodAndArgsCaller;

     label1:
        r4 = r0.<com.android.internal.os.ZygoteInit$MethodAndArgsCaller: java.lang.reflect.Method mMethod>;

        r5 = newarray (java.lang.Object)[1];

        $r6 = r0.<com.android.internal.os.ZygoteInit$MethodAndArgsCaller: java.lang.String[] mArgs>;

        r5[0] = $r6;

        virtualinvoke r4.<java.lang.reflect.Method: java.lang.Object invoke(java.lang.Object,java.lang.Object[])>(null, r5);

     label2:
        return;

     label3:
        $r8 := @caughtexception;

        r3 = $r8;

        $r9 = new java.lang.RuntimeException;

        specialinvoke $r9.<java.lang.RuntimeException: void <init>(java.lang.Throwable)>(r3);

        throw $r9;

     label4:
        $r10 := @caughtexception;

        r1 = $r10;

        r2 = virtualinvoke r1.<java.lang.reflect.InvocationTargetException: java.lang.Throwable getCause()>();

        $z0 = r2 instanceof java.lang.RuntimeException;

        if $z0 == 0 goto label5;

        $r13 = (java.lang.RuntimeException) r2;

        throw $r13;

     label5:
        $z1 = r2 instanceof java.lang.Error;

        if $z1 == 0 goto label6;

        $r12 = (java.lang.Error) r2;

        throw $r12;

     label6:
        $r11 = new java.lang.RuntimeException;

        specialinvoke $r11.<java.lang.RuntimeException: void <init>(java.lang.Throwable)>(r1);

        throw $r11;

        catch java.lang.IllegalAccessException from label1 to label2 with label3;
        catch java.lang.reflect.InvocationTargetException from label1 to label2 with label4;
    }
}
